### ISSUE TITLE
Logo icon does not appear

### ISSUE THREAD

**Issue by mikeerickson** [ntavelis/pretty-mix-notifications#1]
I have been able to define custom `successIcon` and `failIcon` but when defining `logo` it just displays the default thumbsUp icon.

FWIW, this issue also exists in your associated module (https://github.com/ntavelis/webpack-build-notifications#readme) so fixing it there would likely fix it in this package as well.

I know you are using `node-notifier` under the hood and it states the logo (they refer to `icon`) requires an absolute path.

https://github.com/mikaelbr/node-notifier/blob/master/example/advanced.js

If I use `icon` it still does not work

```
  ...
  icon: path.resolve('./resources/assets/cd-logo.png'),
```

Regardless of what is used, the thumbsUp icon is always displayed

**Comment by ntavelis** [comment]
Hello,

It seems like that you are not using the correct key. To override the success icon you need to do this.

`
.prettyNotifications(
        {
          successIcon: path.resolve("./success.png")
        }
    );
`

When you call prettyNotifications fucntion, you pass you custom config that will override the default. `warningIcon` to override the warning icon.

I am closing this, let me know how it goes.

Thank you

**Comment by mikeerickson** [comment]
@ntavelis The success icon is not the issue, that works fine.  My issue is that the defined `logo` icon is not correct.  In all cases, the thumbsUp icon is displayed.  I can get you a screenshot later when I return to the computer.

In addition, reading the `node-notifier` documentation, it labels it as `icon` which I have also tried without success.
